name: CF challenge test (temporary)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install playwright
        run: |
          npm i --no-save playwright-core playwright
          npx playwright install chromium --with-deps

      - name: Browser challenge test
        run: node .github/workflows/_cf-test.mjs
